Switch to build with unixodbc exclusively
Getting errors
```
In file included from /usr/local/include/sqlucode.h:784:
/usr/local/include/sqlext.h:1790:19: error: conflicting types for 'SQLDriverConnectW'
 1790 | SQLRETURN SQL_API SQLDriverConnect(
      |                   ^
/usr/local/include/sqlucode.h:765:26: note: expanded from macro 'SQLDriverConnect'
  765 | #define SQLDriverConnect        SQLDriverConnectW
      |                                 ^
/usr/local/include/sqlucode.h:257:19: note: previous declaration is here
  257 | SQLRETURN SQL_API SQLDriverConnectW(
      |                   ^
```
trying to see if switching to ARM macOS will fix the issue.